/*
 * gameplay.h
 *
 *  Created on: Dec 20, 2023
 *      Author: nds
 */
#pragma once

#include <stdio.h>
#include <nds.h>
#include "Map.h"
#include "P_Util.h"
#include "Controls.h"
#include "Game.h"

#define	WHITE ARGB16(1,31,31,31)
#define	RED ARGB16(1,31,0,0)
#define	BLUE ARGB16(1,0,0,31)

#define MAXWEB 999999
#define MINZMAP 0
#define MAXZMAP 10000

/*
 * This function returns an xyz of the acceleration generated by the rope
 */
Pos RopeTension(Player* player, Pos* grip);
